name: flutter_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expandable: ^4.1.4
  meet_network_image: ^0.1.2
  responsive_builder: ^0.3.0
  syncfusion_flutter_charts: ^18.4.46

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.jpg
  #   - images/a_dot_ham.jpeg
  